### ISSUE TITLE
Cannot debug the project

### ISSUE THREAD

**Issue by khoaho** [Vj3k0/ea-todo#1]
Hi Vjekoslav,

Can you please check the below screenshot to see why I cannot debug the project. This project was built and run successfully in Windows 10. However, it causes error in debugging on Visual Studio Code.

> "Error: Cannot find module 'electron'\n    at Function.Module._resolveFilename (module.js:440:15)\n    at Function.Module._load (module.js:388:25)\n    at Module.require (module.js:468:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (C:\Data\GitHub\ea-todo\app\node_modules\electron-squirrel-startup\index.js:4:11)\n    at Module._compile (module.js:541:32)\n    at Object.Module._extensions..js (module.js:550:10)\n    at Module.load (module.js:458:32)\n    at tryModuleLoad (module.js:417:12)\n    at Function.Module._load (module.js:409:3)"

I updated launch.json to allow debugging: `"program": "${workspaceRoot}/app/main.js",`

![image](https://cloud.githubusercontent.com/assets/1810890/17911578/d4a003ec-6953-11e6-9d0e-ac858030d125.png)

Thank you.

**Comment by Vj3k0** [comment]
Hello khoaho,

in launch.json you didn't specify `runtimeExecutable` or `runtimeArgs`. If you don't specify it, you're running it as NodeJS application, not Electron, so it fails to get Electron module.

So try this:

```
"runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
"runtimeArgs": [
        "${workspaceRoot}/app/main.js"
]
```

This is equivalent of running electron in terminal, and passing path to script or folder where your package.json is.

Cheers!

**Comment by khoaho** [comment]
Hi Vjekoslav,

It works nicely as expected. Thank you very much!

I read your blog http://electron.rocks/. It is awesome to get started with Electron.

Thank you,
Khoa
