### ISSUE TITLE
Fail to package and distribute in Windows 10 and Ubuntu 16

### ISSUE THREAD

**Issue by khoaho** [Vj3k0/ea-todo#2]
Hi Vjekoslav,

Can you please update the project with electron-packager (https://github.com/electron-userland/electron-packager). I cannot package and distribute the project with `npm run dist` in both Windows 10 and Ubuntu 16. Here is the error message about it:

> Error: Build for OS X is supported only on OS X, please see https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build

Thank you.

**Comment by Vj3k0** [comment]
The message is saying it all. You can publish for OSX only from OSX. From
OSX you can publish for all 3 platforms.

**Comment by khoaho** [comment]
I use electron-packager to test on both Windows 10 and Ubuntu 16:
`electron-packager . --platform=all --arch=all`

The result is:
Windows 10 has four created packages: linux-ia32, linux-x64, win32-ia32 and win32-x64
Ubuntu 16 has three created packages: linux-ia32, linux-x64 and darwin-x64

So we can use Windows 10 to build packages for Windows and Linux, Ubuntu for Linux and OSX.

I don't have a Mac machine to test.

**Comment by khoaho** [comment]
I've just installed Wine (https://wiki.winehq.org/Ubuntu), then run electron-packager again `electron-packager . --platform=all --arch=all` in Ubuntu 16. All the packages in Windows, Linux and OSX are created!

eatodo-win32-ia32
eatodo-win32-x64
eatodo-linux-ia32
eatodo-linux-x64
eatodo-darwin-x64
eatodo-mas-x64

The interesting thing is the ia32 and x64 builds from Windows not work on Windows. While the ia32 and x64 builds from Linux works on Windows.

You may update the package.json to add support for electron-packager.

Thank you.

**Comment by Vj3k0** [comment]
This project is using electron-builder, not packager directly.

**Comment by khoaho** [comment]
It's good to know that we can use both electron-builder and electron-packager to build/package the project.
